name: Test CWB

on:
  pull_request:
    branches:
      - main
    paths:
      - 'cwb'
      - 'lib/**'
      - 'scripts/**'
      - '.github/workflows/test-cwb.yml'

concurrency:
  group: test-cwb-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-cwb:
    name: test-cwb
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y zsh

      - name: Run cwb bash tests
        run: bash scripts/test_cwb.sh
